package staff;

import lombok.Getter;
import lombok.Setter;

import java.time.DayOfWeek;
import java.util.HashMap;
import java.util.UUID;

@Getter // Lombok annotation to generate all getters
public class Nurse implements StaffMemberInterface {

    private final UUID id; // Final, so only getter needed (generated by @Getter)
    private final Role role; // Final, so only getter needed (generated by @Getter)

    @Setter // Lombok annotation to generate setter for name
    private String name;

    @Setter // Lombok annotation to generate setter for regularHourlyWage
    private double regularHourlyWage;

    @Setter // Lombok annotation to generate setter for overtimeMultiplier
    private double overtimeMultiplier;

    // Schedule is managed via methods, not direct getter/setter for the HashMap itself
    // to maintain control (e.g., returning a copy).
    private final HashMap<DayOfWeek, Shift> schedule;

    public Nurse(UUID id, String name, Role nurseRole, double regularHourlyWage, double overtimeMultiplier) {
        if (nurseRole == null || !Role.isNurseRole(nurseRole)) {
            throw new IllegalArgumentException("The provided role '" + nurseRole + "' is not a valid nurse role for a Nurse object.");
        }
        this.id = id;
        this.name = name;
        this.role = nurseRole;
        this.regularHourlyWage = regularHourlyWage;
        this.overtimeMultiplier = overtimeMultiplier;
        this.schedule = new HashMap<>(7 * 4);
    }

    public Nurse(String name, Role nurseRole, double regularHourlyWage, double overtimeMultiplier) {
        this(UUID.randomUUID(), name, nurseRole, regularHourlyWage, overtimeMultiplier);
    }

    // Explicit implementation for getSchedule to return a copy, as @Getter would return the direct reference.
    @Override
    public HashMap<DayOfWeek, Shift> getSchedule() {
        return new HashMap<>(this.schedule);
    }

    @Override
    public void assignShift(DayOfWeek day, Shift shiftType) {
        if (day == null) {
            throw new IllegalArgumentException("Day cannot be null when assigning a shift.");
        }
        this.schedule.put(day, shiftType);
    }

    @Override
    public void resetSchedule() {
        this.schedule.clear();
    }

    @Override
    public Shift getShiftOnDay(DayOfWeek day) {
        return this.schedule.get(day);
    }
}